export default {
  plurals: [
    [/$/, 's'],
    [/s$/i, 's'],
    [/^(ax|test)is$/i, '$1es'],
    [/(vir|alumn|foc|radi|succub|styl|syllab|fung|termin|uter)(us|i)$/i, '$1i'],
    [/^(alumn|formul)(ae?)$/, '$1ae'],
    [/^(addend|memorand|ov|spectr)(um|a)$/, '$1a'],
    [/^(stigm|tom|schem)(a|ata)$/, '$1ata'],
    [/^(automat|criteri|phenomen|polyher)(on|a)$/, '$1a'],
    [/(octop)us$/i, '$1odes'],
    [/(octop)odes$/i, '$1odes'],
    [/(alias|status)$/i, '$1es'],
    [/(bu)s$/i, '$1ses'],
    [/^(cant|heter|phot|zer|pian|portic|pr|quart|kimon)o$/i, '$1os'],
    [/o$/i, '$oes'],
    [/([ti])um$/i, '$1a'],
    [/([ti])a$/i, '$1a'],
    [/sis$/i, 'ses'],
    [/(?:([^f])fe|([lr])f)$/i, '$1$2ves'],
    [/(hive)$/i, '$1s'],
    [/([^aeiouy]|qu)y$/i, '$1ies'],
    [/(x|ch|ss|sh)$/i, '$1es'],
    [/(matr|vert|ind)(?:ix|ex)$/i, '$1ices'],
    [/^(m|l)ouse$/i, '$1ice'],
    [/^(m|l)ice$/i, '$1ice'],
    [/^([bv]?ox)$/i, '$1en'],
    [/^((?:[bv]?ox)en)$/i, '$1'],
    [/(quiz)$/i, '$1zes'],
    [/^(air|water|space|hover)craft$/i, '$1craft'],
    [/man$/, 'men'],
    [/men$/, 'men']
  ],

  singular: [
    [/s$/i, ''],
    [/(ss)$/i, '$1'],
    [/(n)ews$/i, '$1ews'],
    [/([ti])a$/i, '$1um'],
    [/((a)naly|(b)a|(d)iagno|(p)arenthe|(p)rogno|(s)ynop|(t)he)(sis|ses)$/i, '$1sis'],
    [/(^analy)(sis|ses)$/i, '$1sis'],
    [/([^f])ves$/i, '$1fe'],
    [/(hive)s$/i, '$1'],
    [/(tive)s$/i, '$1'],
    [/([lr])ves$/i, '$1f'],
    [/([^aeiouy]|qu)ies$/i, '$1y'],
    [/(s)eries$/i, '$1eries'],
    [/(m)ovies$/i, '$1ovie'],
    [/(x|ch|ss|sh)es$/i, '$1'],
    [/^(m|l)ice$/i, '$1ouse'],
    [/(bus)(es)?$/i, '$1'],
    [/(o)es$/i, '$1'],
    [/(shoe)s$/i, '$1'],
    [/(cris|test)(is|es)$/i, '$1is'],
    [/^(a)x[ie]s$/i, '$1xis'],
    [/(vir|alumn|foc|radi|succub|styl|syllab|fung|termin|uter)(us|i)$/i, '$1us'],
    [/^(alumn|formul)(ae?)$/, '$1a'],
    [/^(addend|memorand|ov|spectr)(um|a)$/, '$1um'],
    [/^(stigm|tom|schem)(a|ata)$/, '$1a'],
    [/^(automat|criteri|phenomen|polyher)(on|a)$/, '$1on'],
    [/(octop)(us|odes)$/i, '$1us'],
    [/(alias|status)(es)?$/i, '$1'],
    [/^([bv]?ox)en/i, '$1'],
    [/(vert|ind)ices$/i, '$1ex'],
    [/(matr)ices$/i, '$1ix'],
    [/(quiz)zes$/i, '$1'],
    [/(database)s$/i, '$1'],
    [/^(air|water|space|hover)craft$/, '$craft'],
    [/men$/, 'man']
  ],

  irregularPairs: [
    ['person', 'people'],
    ['sex', 'sexes'],
    ['move', 'moves'],
    ['cow', 'kine'],
    ['zombie', 'zombies'],
    ['inuk', 'inuit'],
    ['inukshuk', 'inukshit'],
    ['iqalummiuq', 'iqalummiut'],
    ['nunavimmiuq', 'nunavimmiut'],
    ['nunavummiuq', 'nunavummiut'],
    ['foot', 'feet'],
    ['goose', 'geese'],
    ['tooth', 'teeth'],
    ['child', 'children'],
    ['die', 'dice'],
    ['phalanx', 'phalanges']
  ],

  uncountable: [
    'equipment',
    'information',
    'rice',
    'money',
    'species',
    'series',
    'fish',
    'sheep',
    'jeans',
    'police',
    'moose',
    'ninja',
    'bison',
    'deer',
    'duck',
    'plankton',
    'salmon',
    'squid',
    'swine',
    'trout',
    'benshi',
    'otaku',
    'samurai',
    'māori',
    'maori'
  ]
};